/****************************************************************

  Generated by Vortex Lite IDL to C Translator
  File name: FTP.h
  Source: FTP.idl
  Generated: Fri Aug 04 13:50:42 CST 2017
  Vortex Lite: V2.0.7

*****************************************************************/

#include "dds.h"

#ifndef _DDSL_FTP_H_
#define _DDSL_FTP_H_


#ifdef __cplusplus
extern "C" {
#endif


typedef struct FTP_File
{
  char * path;
  uint16_t seq_num;
  dds_sequence_t payload;
  bool is_done;
} FTP_File;

extern const dds_topic_descriptor_t FTP_File_desc;

#define FTP_File__alloc() \
((FTP_File*) dds_alloc (sizeof (FTP_File)));

#define FTP_File_free(d,o) \
dds_sample_free ((d), &FTP_File_desc, (o))

#ifdef __cplusplus
}
#endif
#endif /* _DDSL_FTP_H_ */
