/****************************************************************

  Generated by Vortex Lite IDL to C Translator
  File name: FTP.c
  Source: FTP.idl
  Generated: Fri Aug 04 13:50:42 CST 2017
  Vortex Lite: V2.0.7

*****************************************************************/
#include "FTP.h"


static const dds_key_descriptor_t FTP_File_keys[1] =
{
  { "path", 0 }
};

static const uint32_t FTP_File_ops [] =
{
  DDS_OP_ADR | DDS_OP_TYPE_STR | DDS_OP_FLAG_KEY, offsetof (FTP_File, path),
  DDS_OP_ADR | DDS_OP_TYPE_2BY, offsetof (FTP_File, seq_num),
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_1BY, offsetof (FTP_File, payload), 0,
  DDS_OP_ADR | DDS_OP_TYPE_BOO, offsetof (FTP_File, is_done),
  DDS_OP_RTS
};

const dds_topic_descriptor_t FTP_File_desc =
{
  sizeof (FTP_File),
  sizeof (char *),
  DDS_TOPIC_NO_OPTIMIZE,
  1u,
  "FTP::File",
  FTP_File_keys,
  FTP_File_ops,
  "<MetaData version=\"1.0.0\"><Module name=\"FTP\"><Struct name=\"File\"><Member name=\"path\"><String/></Member><Member name=\"seq_num\"><UShort/></Member><Member name=\"payload\"><Sequence><Octet/></Sequence></Member><Member name=\"is_done\"><Boolean/></Member></Struct></Module></MetaData>"
};
